### PR TITLE
Fixed deviantArt ripping

### PR DESCRIPTION
**Pull request by Wiiplay123**
Uses the data-super-full-img attribute of thumbnails as first attempt to
get a full image URL. If that doesn't work (as is the case with mature
items), the JSON is used. thumbToFull is still broken in this commit,
but shouldn't be needed.

EDIT: Sorry, description ripping doesn't work. I'll submit a pull request when that's fixed.

### CODE REVIEW

**Comment by Wiiplay123** [comment]
Ok I added a commit to fix description ripping, sorry about that!

**Comment by cyian-1756** [comment]
Some minor issues I found with this, sometimes jpg images are saved as png (test link http://the-moonbound.deviantart.com/gallery/54059714/Fanart) and description names and image titles often don't match 

Also downloading http://the-moonbound.deviantart.com/gallery/ errors out with `No images found at http://the-moonbound.deviantart.com/gallery/?coffset=10` and not all images are downloaded

**Comment by Wiiplay123** [comment]
Which images are supposed to be jpg? Also, I'll change the description code to allow for better control of description file names when I have the time.

**Comment by cyian-1756** [comment]
@Wiiplay123 

> Which images are supposed to be jpg? 

A couple of them are

http://the-moonbound.deviantart.com/art/Patreon-Ysuria-665738363

http://the-moonbound.deviantart.com/art/Patreon-Lenina-650165992

http://the-moonbound.deviantart.com/art/C-Shareel-and-Elveren-649050384

**Comment by Wiiplay123** [comment]
The jpg is a lower resolution version of the original image, which is a png. That's why it's downloading a png instead of a jpg. To see this, you can right-click on the image and press "view image" without zooming in, then zoom in and press "view image" again and compare the two resolutions.

**Comment by cyian-1756** [comment]
@Wiiplay123 

> That's why it's downloading a png instead of a jpg.

No it's downloading a jpg and naming it as if it were a png. Running the `file` command on one of them outputs

`9c5f752317bb2ea1abf5b417f6baf379-daht74o.png: JPEG image data, JFIF standard 1.01, resolution (DPCM), density 28x28, segment length 16, baseline, precision 8, 737x1083, frames 3`

So on disk it is a JPEG but named as if it were a png (Which breaks a lot of image viewers).

**Comment by Wiiplay123** [comment]
Ok that actually does seem to be downloading the lower res jpeg for some images, but the actual URL says it's a png. Gonna have to make it manually detect what kind of image it is unless I can find a way to fix this. Also, is there any way to get the orig(xx).deviantart.com link using the pre(xx).deviantart.com link? That would be really helpful for downloading the full resolution correctly.

**Comment by cyian-1756** [comment]
> Also, is there any way to get the orig(xx).deviantart.com link using the pre(xx).deviantart.com link? 

AFAIK there's not.

**Comment by Wiiplay123** [comment]
Looks like there's a link to the original image in the actual image page, but I need to find a way to get past the age gate to actually get the link for mature images. :|

**Comment by Wiiplay123** [comment]
I've found a way to bypass the age gate when not logged in, just needs to have a cookie that says "agegate_state=1" in the header. From there it looks easy to get the full image, but I haven't finished programming a new commit to fix it yet, might have it done in a couple days.

**Comment by Wiiplay123** [comment]
New problem, that "full-sized" image isn't always the original, sometimes it's a size between the zoomed out image and the original, in cases where the artist didn't set the display resolution to original. Example is an image I found on reddit: http://evehly.deviantart.com/art/Ombre-677357037

Finding a way to get the download button should fix it, but I need to figure out what causes the download button to redirect to the exact same page it started from first.

**Comment by Wiiplay123** [comment]
Ok, it will only have to find the download button if the data-super-full-img value doesn't link to the original image, which should save some time and bandwidth. If it finds the download button, it will send an HTTP request for it but not actually download anything, in order to adjust for redirects. If it can't find the full size image, it will fall back on the next best thing.

THIS is where I need to continue fixing the code before my next commit, because if an artist doesn't allow downloading and there's no original image link, it might fall back on an image that doesn't match the file extension of the link. The only way to fix this that I can find would be to change the DownloadFileThread code to check the mimetype and change the file extension to match. I'll upload the current commit when it's done and someone else can figure out what to do from there.

**Comment by Wiiplay123** [comment]
Ok, I still need to do some testing on this latest commit to see if it works now. If it works, I may have it done by tomorrow. The saving jpg as png still isn't fixed but it should show up a lot less now that it can find the images that are higher resolution and save them instead.

**Comment by rautamiekka** [comment]
You should read https://github.com/4pr0n/ripme/pull/441#issuecomment-278629504

**Comment by Wiiplay123** [comment]
Which part of it? I've adjusted the code for everything you mention in the comment that you linked, except for the thing at the very bottom about the cookies and tokens.

**Comment by NCCAG** [comment]
Hello, I do not have programming skills. Could someone tell me how to use this fix?

**Comment by Wiiplay123** [comment]
I made a release for the latest version of ripme_da_desc, just download the jar and it should work.
https://github.com/Wiiplay123/ripme_da_desc/releases/tag/1.4.9-x1

**Comment by NCCAG** [comment]
thank you very much

**Comment by Wiiplay123** [comment]
After testing the ripper by ripping lots of the things I wanted to rip but never got a chance to because ripme was broken, it looks like the downloading jpgs by accident problem is solved for most cases, haven't had it happen even once in all the galleries that I've been downloading!

Also, it looks like I'm downloading images at the end of galleries that it missed before, so I'm guessing there must have been some issue previously with the main version stopping it from downloading all the images before I made all these patches. One thing I would still like is to have the login actually work :|

**Comment by Wiiplay123** [comment]
After testing the ripper by ripping lots of the things I wanted to rip but never got a chance to because ripme was broken, it looks like the downloading jpgs by accident problem is solved for most cases, haven't had it happen even once in all the galleries that I've been downloading!

Also, it looks like I'm downloading images at the end of galleries that it missed before, so I'm guessing there must have been some issue previously with the main version stopping it from downloading all the images before I made all these patches. One thing I would still like is to have the login actually work :|

**Comment by NCCAG** [comment]
I've been testing the program and it works fine, but I can not figure out how to save the files in their corresponding folders. Was the option disabled?

**Comment by cyian-1756** [comment]
@NCCAG 

> but I can not figure out how to save the files in their corresponding folders.

What exactly are you trying to do?

**Comment by Wiiplay123** [comment]
I'm gonna get to work on fixing the FurAffinity ripper, now that deviantArt works on my repo. Hopefully I can get descriptions finally working without breaking the entire ripper this time.

**Comment by Hrxn** [comment]
Including favorites, i.e. `http://{profile-name}.deviantart.com/favourites/`?

**Comment by NCCAG** [comment]
cyian-1756, I am trying to download specific folders from the deviantart gallery user. For example:
http://negg22.deviantart.com/gallery/

-Sketches: with two images
-AMG: with one image.
-And two unclassified images

I was looking for a program that created the same directory structure that Deviantart

Years ago there was a program that did that, but it is outdated: Http://dragoniade.deviantart.com/journal/deviantART-Favorites-downloader-1-2-0-is-out-219389762

**Comment by cyian-1756** [comment]
@NCCAG It seems like saving the directory structure ought be something that the ripper should do (I'll check it out more in depth after the ripper get merged into master)

As a quick work around for the photos in galleries you can just download from the gallery url (something like http://negg22.deviantart.com/gallery/9145326/Sketches). However it doesn't seem to be any such url for the unclassified items

**Comment by NCCAG** [comment]
oks, thank you so much for everything

**Comment by metaprime** [comment]
Hey all, there's been a lot of discussion here, can someone tell me where we landed? Does this PR appear to fix DeviantART? (We've had a number of attempts that didn't quite work.)

**Comment by metaprime** [comment]
In particular how does this compare to #441

**Comment by NCCAG** [comment]
This release downloads all the images, but does not preserve the directory structure.
https://github.com/Wiiplay123/ripme_da_desc/releases/tag/1.4.9-x1

**Comment by rautamiekka** [comment]
If Travis is failing the compilation by saying, among others, that login form at DA was correctly submitted, it can't work any better outside the compiler either.

**Comment by metaprime** [comment]
@rautamiekka the CI has been broken for a long time. I'm planning on fixing it up at some point as soon as I can figure out why it fails on Travis even when it passes on my machine. That said, there might be new issues that I've been ignoring since the CI is always failing -- one of the downsides of a broken CI.

**Comment by rautamiekka** [comment]
^ That's weird. In comparison https://github.com/coelckers/gzdoom uses AppVeyor and Travis at the same time without such problems.

**Comment by Wiiplay123** [comment]
I'm experimenting with journal ripping now, in a third branch called da_journal. It's not fully tested yet, so I'll keep testing it and making sure everything works ok.

**Comment by metaprime** [comment]
@rautamiekka Yeah, it's definitely weird. A lot of projects have no problem. I think it might have something to do with the test environment, the fact that the tests might download large amounts of data (even in test mode).

That said there's a ton of tests that are legitimately failing right now. "Failing on Travis but not on my machine" was as of the last time I looked into it, which was around the time I took over this project in late December.

**Comment by metaprime** [comment]
@Wiiplay123 sounds good. I'm merging this PR.

**Comment by rautamiekka** [comment]
@metaprime Probly comparing and deeply researching the parameters and their values will help, and/or maybe downloading less data at once and in total and deleting previously successfully downloaded data will help.

**Comment by rautamiekka** [comment]
@metaprime Probly comparing and deeply researching the parameters and their values will help, and/or maybe downloading less data at once and in total and deleting previously successfully downloaded data will help.

After all, RipMe is the only project I can think of which actually fetches or otherwise generates data during compilation-time testing.

**Comment by metaprime** [comment]
@rautamiekka Agreed, but it's going to take some researching, and maybe re-implementing how the tests work in the first place. However, a lot of projects generate some sort of test logs, so if we saved URLs only that might help, but yes, I think the main problem is probably that we fetch a lot of data from the web.

**Comment by rautamiekka** [comment]
^ Test logs are the mandatory evil usually not taking much space and didn't even occur to me.

**Comment by metaprime** [comment]
Anyway see #374 (we should probably continue the discussion there)

**Pull request merged**
