### PR TITLE
attempt at fixing issue #330 instagram api changes

### PR DESCRIPTION
**Pull request by JoshKastang**
Strip out the irrelevant iconosquare logic and implements support for the new instagram json structure. Minor testing this appears to be working as expected, but I am sure there is room for improvements.

### CODE REVIEW

**Comment by sleaze** [comment]
Hey @JoshKastang, FYI I've merged your great functionality introduced with this PR into the master branch of my fork: https://github.com/sleaze/ripme

Cheers!

**Comment by JoshKastang** [comment]
Thanks @sleaze. Are you planning on taking over development of ripme moving forward? If so I will start adding Pull Requests fork as well.

**Comment by Gaboso** [comment]
Hi @JoshKastang, i liked the functionality you implemented and i also found it very useful. So I added it to my fork https://github.com/Gaboso/ripme.

**Comment by UnforeseenOcean** [comment]
Recent update caused RipMe (Sleaze version) to download and continuously open url.txt (containing links for images and media).
Please investigate!

**Pull request merged**
