### PR TITLE
Hentai Foundry rip fixes and Y!Gallery ripper

### PR DESCRIPTION
**Pull request by Phenrei**
Rolled these two into one pull request as they both edit the same file (DownloadFileThread) for file format fallback support. Brings both rippers up to the ability to rip all the images available from a user or gallery on both sites.

If you can think of a way to do the file format support in a way other than adding it to DownloadFileThread feel free to edit the pull; it seemed to me there was no higher level place to attempt the fallback feature in the ripper itself because those have no access to the observer or the 404 error on the file (and either way it was cleaner without needless error messages for files successfully downloaded in another format.

For HF: Added login to display kink images (default account shows all, gives 300 images per page, and sorts old to new), fixes small bug with usernames starting with a number/symbol, and provides file format fallback (default assumes .jpg, it can be up to 4 file types; this had to be hacked into DownloadFileThread as I couldn't find another place to do the check)

For the new Y!Gallery Ripper: New feature complete ripper with login to display porn images (a default account will need to be provided), image names in the filename (parsed from the same page as image URLs), and subgallery support (both directly linked and nested within base gallery links)

### CODE REVIEW

**Comment by UnforeseenOcean** [comment]
I wanted a y!Gallery ripper (and went on to Pull Request and saw this one) and I was fascinated with your creation.
I really appriciate it, by the way. (While TumbleOne did not support Batch Downloading, this did)

Is there any way to rip that site? I could've brute forced it with WinHTTrack but...you know. It takes up too much space and the overall quality is really low since it cannot rip full-size image.

p.s. Request incoming

**Comment by metaprime** [comment]
@Phenrei Why did you close this? Was functionality already implemented or are you working on a replacement?

**Comment by Phenrei** [comment]
@metaprime It's a very hacky implementation on a very old code base that I have made a better version of on my personal fork which, time permitting, I will clean into a more reasonable pull request now that I'm working on enhancing this again. It will have more universal support for the file format fallback for images style of download (instead of going per-page like some rippers), which is especially useful on rate-limited sites where the data is parsable from the thumbnail pages like some boorus I have implemented rippers for, like sankaku channel.

**Comment by metaprime** [comment]
@Phenrei sounds good, looking forward to seeing your new work when you've got it cleaned up.

**Pull request closed without merging**
