### PR TITLE
Update to Java 8 and fixed various code smells

### PR DESCRIPTION
**Pull request by Gaboso**
Updated icons;
Indent corrected in various files;
Updated version of java to 1.8;
Add log4j in various files;
Fixed some code smell;
Updated version of maven dependencies.

### CODE REVIEW

**Comment by metaprime** [comment]
I really appreciate this effort but this is a huge PR and I suspect it's going to have a lot of conflicts, or will have more conflicts when other PRs are merged in.

Since I don't necessarily want to rely on the authors of every other PR to return and fix up their PRs, I'll try to get all the other PRs merged in before taking this one.

**Comment by metaprime** [comment]
I'm lukewarm on the concept of moving to Java 1.8. It potentially breaks backwards compatibility with users who are not on the latest JRE (or at least who are not using any version of JRE 1.8 or later) and I don't think we need to use any of the new language features added since 1.6.

**Comment by Gaboso** [comment]
@metaprime I'm updating the project and trying to keep it in sync with the updates that are made here in your repository.
Also, I'm using SonarQube to try to improve some parts of the code and also trying to make the existing unit tests work.

**Comment by metaprime** [comment]
@Gaboso -- I'd invite you to make any small improvements as independent changes that can be merged in quickly. If you make them part of an already-huge PR they may never make it into mainlain. The time I have available for code review is quite limited :)

**Pull request closed without merging**
