### PR TITLE
Added EroShare Ripper and Fixed Vidble Ripper

### PR DESCRIPTION
**Pull request by blth**
EroShare ripper works with reddit user profile submissions and as a stand alone from EroShare

### CODE REVIEW

**Comment by kanink007** [comment]
compiling error with maven

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile 
(default-compile) on project ripme: Compilation failure
[ERROR] .../ripme-master/src/main/java/com/rarchives/ripme/utils/RipUtils.java:[85,31] cannot find symbol
[ERROR] symbol:   variable EroShareRipper
[ERROR] location: class com.rarchives.ripme.utils.RipUtils

**Comment by blth** [comment]
Thank you kanink007 I have updated the utils file to correct this issue.

**Comment by blth** [comment]
Fixed Vidble Ripper to include vidle.com/show/ images.

**Comment by 4pr0n** [comment]
Resolving in favor of https://github.com/4pr0n/ripme/pull/319

If this should stay open, feel free to reopen it.

**Pull request closed without merging**
