### PR TITLE
Eroshare can now rip profiles

### PR DESCRIPTION
**Pull request by cyian-1756**
Test link https://eroshare.com/u/onlybestones

### CODE REVIEW

**Comment by Hrxn** [comment]
BTW, what format/quality options does Eroshare support?

**Comment by cyian-1756** [comment]
@Hrxn No idea

**Comment by Hrxn** [comment]
Well, the web player on the site only lists _HD_ and _SD_, as it seems.

Is that what you are extracting from the source?

**Comment by cyian-1756** [comment]
@Hrxn 

> Is that what you are extracting from the source?

Again I have no idea. I didn't even check the video ripping logic I just added a regex, canRip() and a for loop so it could rip from profile pages.

**Comment by metaprime** [comment]
@cyian-1756 This doesn't seem to work with the rip URLs only option enabled but that wasn't worth blocking the merge.

**Comment by metaprime** [comment]
Released in 1.4.20: https://github.com/4pr0n/ripme/releases/tag/1.4.20

**Pull request merged**
