### PR TITLE
Instagram Cropped Photo Fix

### PR DESCRIPTION
**Pull request by JoshKastang**
This should fix the cropping issues reported in #519 and #499. It appears IG is adding support for higher resolution images but artificially limiting the size to 1080x1080px on the API level. My best guess is to retain support for legacy applications.

### CODE REVIEW

**Comment by poiuyrt546** [comment]
This issue still persists for me in the latest version 1.4.14.

Images in higher res are getting cropped to 1080*1080px.

**Comment by metaprime** [comment]
@poiuyrt546 This fixed the issues I was looking out for on my end. The resulting pictures were still not larger than 1080x1080. Can you provide an example link?

**Comment by poiuyrt546** [comment]
@metaprime 
https://www.instagram.com/p/BSRkfQEgP-S/?taken-by=noteworthycollective

I'm getting 1080x1080px version for this 1080x1350px image.

**Comment by JoshKastang** [comment]
There is another URI parameter, `c0.135.1080.1080` - I was only accounting for `c0.135.1080.1080` as the general use case. Before issuing another patch i could use a larger subset of cases to see if we can develop a regex to handle this.

**Comment by metaprime** [comment]
@JoshKastang I recommend opening a new issue to track this.

**Pull request merged**
