### PR TITLE
Minor css updates to Furaffinity ripper

### PR DESCRIPTION
**Pull request by cyian-1756**
I made a minor update so that images will rip again fixing one part of [479](https://github.com/4pr0n/ripme/issues/479)

test link 

https://www.furaffinity.net/gallery/miles-df/

### CODE REVIEW

**Comment by metaprime** [comment]
For me, output directory looks like this (has it always been this way for this ripper?):

```
'001_ 22824584.txt'  '025_ 17613425.txt'  1374153143.miles-df_summergirl.jpg                      1442339312.miles-df_cynfall_conglamerate.jpg
'002_ 22743993.txt'  '026_ 17167788.txt'  1378241083.miles-df_life_throught_a_lens__pnb_.jpg      1444407233.miles-df_laikaboss__tracer_cosplay_.jpg
'003_ 22636107.txt'  '027_ 16931738.txt'  1379335775.miles-df_flame.jpg                           1447174703.miles-df_chloe__fa_version_wear_.jpg
'004_ 22581206.txt'  '028_ 16796369.txt'  1383994754.miles-df_pinkie_pie_underground.jpg          1453416497.miles-df_blackfang.jpg
'005_ 22495394.txt'  '029_ 16409495.txt'  1385934224.miles-df_get_fit_girl.jpg                    1456245114.miles-df_corona_king_2.jpg
'006_ 22411640.txt'  '030_ 16389287.txt'  1389022261.miles-df_mellany_mellows.jpg                 1457897654.miles-df_cinnamon.jpg
'007_ 22251946.txt'  '031_ 16382508.txt'  1389143095.miles-df_bang_.jpg                           1458835560.miles-df_babe_wolf.jpg
'008_ 22098046.txt'  '032_ 16292536.txt'  1391785959.miles-df_kung_fury.jpg                       1458931779.miles-df_finnick_in_da_house.jpg
'009_ 21809469.txt'  '033_ 15318856.txt'  1394143194.miles-df_hb_gift_for_yulliandress.jpg        1465927925.miles-df_hazel_punkin_3__black_widow_cosplay_.jpg
'010_ 21521884.txt'  '034_ 14704255.txt'  1401752211.miles-df_knight_rider.jpg                    1467217906.miles-df_varry_preez.jpg
'011_ 21501751.txt'  '035_ 14424321.txt'  1402502526.miles-df_hello_beach.jpg                     1469895307.miles-df_remitost.jpg
'012_ 21360156.txt'  '036_ 13872172.txt'  1403372102.miles-df_emily_in_da_city_v1.jpg             1475078640.miles-df_caramel_macchiato.jpg
'013_ 21272621.txt'  '037_ 13784853.txt'  1404245528.miles-df_bat.jpg                             1475862363.miles-df_runa.jpg
'014_ 20709815.txt'  '038_ 13698887.txt'  1409605006.miles-df_unicorn_.jpg                        1477152324.miles-df_investigation.jpg
'015_ 20420821.txt'  '039_ 13624529.txt'  1412540693.miles-df_biscuit.jpg                         1477332531.miles-df_zabivaka.jpg
'016_ 20277091.txt'  '040_ 12901772.txt'  1419626097.miles-df_shiranai.jpg                        1480004616.miles-df_daughter_of_cerenia.jpg
'017_ 19480785.txt'  '041_ 12689159.txt'  1429143660.miles-df_kai_yun-jun.jpg                     1482686745.miles-df_mustang.jpg
'018_ 19469497.txt'  '042_ 12443583.txt'  1430001855.miles-df_batter_hicane.jpg                   1484084100.miles-df_ninetails.jpg
'019_ 19363204.txt'  '043_ 12431115.txt'  1430069679.miles-df_miles-df_artbook_vol2.jpg           1485454159.miles-df_welcome_to_the_space_jam.jpg
'020_ 19183016.txt'  '044_ 12196963.txt'  1430257051.miles-df_be_my_little_rock_n_roll_queen.jpg  1486141480.miles-df_morta.jpg
'021_ 18859022.txt'  '045_ 12025440.txt'  1433968766.miles-df_ludwig_bullworth_jackson.jpg        1486840312.miles-df_prince.jpg
'022_ 18205796.txt'  '046_ 11614744.txt'  1435268641.miles-df_red.jpg                             1487279758.miles-df_zynn.jpg
'023_ 17910353.txt'  '047_ 11526047.txt'  1437501870.miles-df_chitaury.jpg                        1488211551.miles-df_liru.jpg
'024_ 17690321.txt'  '048_ 11118486.txt'  1441640764.miles-df_pimp_my_ride.jpg                    1488910880.miles-df_lax_junkie.jpg
```

The fact that we have the image counter for the .txt files which I assume are the descriptions, and not for the images themselves, makes it difficult to group them. Additionally, the file name for the text file corresponding to each image should probably be exactly the same as for the images (except for the file extension, of course).

LMK if you want to make any changes here to improve this before I merge this. Otherwise I'll merge this as-is because this is a strict improvement over not working at all.

**Comment by cyian-1756** [comment]
> (has it always been this way for this ripper?):

I just changed the jsoup bits so I assume it's always been this way

> LMK if you want to make any changes here to improve this before I merge this.

I say merge it as it for now, I'll make the changes to it in the next few days

**Comment by cyian-1756** [comment]
@metaprime I made some changes to the file naming, however the file name for the text file still doesn't correspond to each image (Text files are named $TITLE by $ARTIST where as images are $ARTIST_$TITLE). I'll keep working on it but I think that it's safe to merge at this point

**Comment by metaprime** [comment]
@cyian-1756 Yeah since there's no regression, I'll merge this. Feel free to keep working on it. By the way thanks so much for all the dev work you're doing here. Managing all your PRs and the releases hasn't left me much time to do any actual dev work on this (not necessarily a bad thing -- high quality contributions are high quality contributions and this sets up good separation of efforts).

**Comment by cyian-1756** [comment]
@metaprime 

> By the way thanks so much for all the dev work you're doing here.

No problem

**Comment by metaprime** [comment]
Unfortunately, it looks like this doesn't work anymore.

**Pull request merged**
