### PR TITLE
Added a ripper for Chevereto

### PR DESCRIPTION
**Pull request by cyian-1756**
I never was able to get full user page ripping to work so I removed all the code for that and left the code for album ripping.

I also changed the name output to `domain.tld_albumID` 

A few albums to test

https://hushpix.com/album/3JMJ

https://hushpix.com/album/3MxO

https://hushpix.com/album/3u2c

http://tag-fox.com/album/TOjH

### CODE REVIEW

**Comment by metaprime** [comment]
Tested this out, but it looks like it doesn't rip the context from additional pages. For example, your first link, https://hushpix.com/album/3JMJ (BustyGanon) only gets 24 items.

I could merge this as-is with improvements to come in a later pull request, or I could wait until you make some changes. Just let me know.

I'll leave this unmerged for the time being. I'll check back in a day or two.

**Comment by metaprime** [comment]
Also, are there any other sites that use Chevereto that you could provide a link to? For example, link to something on ezphotoshare we could test the ripper on?

**Comment by cyian-1756** [comment]
@metaprime 

> I could merge this as-is with improvements to come in a later pull request, or I could wait until you make some changes. Just let me know.

I'd prefer if you waited until I made some changes, I'd rather not have semi-broken code committed

> Also, are there any other sites that use Chevereto that you could provide a link to? For example, link to something on ezphotoshare we could test the ripper on?

AFAIK ezphotoshare blocks ripping (I meant to remove it but forgot about it), I check for some other sites to test with

I'm a bit busy with work atm so it will take me a day or two to get on this

**Comment by cyian-1756** [comment]
@metaprime I added `getNextPage` so now entire albums download and I added tag-fox.com so there is another site we can test on

Test album for tag-fox: http://tag-fox.com/album/TOjH

**Comment by metaprime** [comment]
Looks good.

I think we should also grab the album titles from the pages while we're at it.

**Comment by cyian-1756** [comment]
@metaprime 

> I think we should also grab the album titles from the pages while we're at it.

I'll get on that tomorrow

**Comment by cyian-1756** [comment]
@metaprime the ripper grabs album titles as well

**Comment by metaprime** [comment]
Sorry for leaving this for so long. Slipped off my radar.

**Pull request merged**
