### PR TITLE
now adds http: before smutty.com links

### LINKED ISSUE #442: Smutty.com looks like they changed their image code. Getting Error: No Protocol
Pretty much as the title says. Looks like the links now start with "//" which is confusing the ripper.

### PR DESCRIPTION
**Pull request by cyian-1756**
This should close #442 

Test url https://smutty.com/h/smuttymodels/

### CODE REVIEW

**Comment by cyian-1756** [comment]
@metaprime can you post the log? Because it's working fine on my machine

**Comment by metaprime** [comment]
```
Downloading http://smutty.com/h/smuttymodels/?q=%23smuttymodels&page=1&sort=date&lazy=1
Rip complete, saved to E:\dev\ripme\rips\smutty_smuttymodels
```

**Comment by cyian-1756** [comment]
@metaprime can you load smutty.com in a browser? Because besides you being unable to reach the site I have no idea what could be causing the ripper to not work for you

**Comment by metaprime** [comment]
@cyian-1756 I guess I didn't post my reply. Yes, I am able to reach the site.

**Comment by stacph** [comment]
For me it still says 'no protocol' :(

no protocol: //s.smutty.com/media_smutty_2/e/l/t/e/p/eltetas78-sih0b-d773b8.jpg

**Comment by metaprime** [comment]
@cyian-1756 is there any reason to keep this open? (I think we decided it was not necessary.)

**Comment by cyian-1756** [comment]
> @cyian-1756 is there any reason to keep this open?

I'm not sure. For whatever reason my PR worked fine for me

**Comment by metaprime** [comment]
@cyian-1756 I tried it again and it seems to work fine... I'll merge it.

**Comment by metaprime** [comment]
Merged as https://github.com/RipMeApp/ripme/commit/1214d191874f4bcee87ca7a54b2560349cc23e0a

**Pull request closed without merging**
