### PR TITLE
Update Deviantart Ripper

### PR DESCRIPTION
**Pull request by Phenrei**
New selects for div structure, new login system (hidden token), Note: account requires old pagination setting (this has been set on default login), thumb fallback still broken (temp fix of try again)

### CODE REVIEW

**Comment by metaprime** [comment]
Do users need to do anything to configure ripme to use this? Do they need to set up an account?

**Comment by rautamiekka** [comment]
^ Generally no acc needed. I just tested you're allowed to see _Mature_-tagged content by clicking one which is covered with silver background and 'Mature Content' on it just to give your birth year.

However, that auto-scroll feature can't be toggled (AFAIS) without an acc.

I have the same content open in 2 windows that aren't logged in. Looking at the source code, the area where the content would appear is replaced by the age verifier, but the piece's sizes are mentioned multiple times regardless of it. Seemingly when there are more than 1 zoom levels, for which there are a separate file each (see below). The download button is its own entity with its own link that seems to always come with a token appended.

These are how I see things looking at the source code:

The way when there's no download button and when the piece is visible:
1) there's a `<div class="dev-view-deviation">` with potentially multiple `Resolution</dt>` and `<dd>X×X</dd>` (where the `X` are integers) directly below it.

**Comment by Phenrei** [comment]
@rautamiekka covers it in more detail than I did, I was just verifying the basic features regarding the existing ripper which assumes an account (like the default one, though who knows if/when it would be locked out) that shows mature posts and has pagination set to the older system.

The existing code for finding original file URLs seemed also to be generally operating as expected (loading the files from links or from the main page if possible), but I did not dig into it that deeply.

**Comment by rautamiekka** [comment]
**There's a 2nd way to get to the stuff:**

While I were looking for how DA's RSS subbing works now (it used to be just a straight RSS link in each folder and gallery, but now the link is totally gone, so you have to know the link first to construct the actual sub' link), http://www.wikihow.com/Bypass-the-Mature-Filter-on-deviantArt explains that, and its primary function: how to bypass Mature tag through RSS.

**Comment by mikalh19** [comment]
I know I'm going to get insulted for this.... but where do I put the updated deviantartripper.java file so that I can actually use it? In a ripme subdirectory? Elsewhere? 
Thanks is advance.

**Comment by rautamiekka** [comment]
^ Java ain't Python. Wait for a new release.

**Comment by angelegg** [comment]
@mikalh19 You need replacing original DeviantartRipper.java with new one.
Then compile with Maven(run bulid.bat)
see how to install Maven on windows.
https://www.youtube.com/watch?v=Jtj-0yhox5s

**Comment by angelegg** [comment]
@Phenrei Thanks! 
It hangs up when downloading next page at some gelleries.
ex.
 http://mariaski.deviantart.com/gallery/?catpath=/

I appreciate your help.

**Comment by metaprime** [comment]
I haven't tested this personally. To be clear, does this change seem to work? Is any action required to get it to work that they should be notified as or does it work out of the box? Is there any follow-up action item we should open an issue to track after this change is merged?

**Comment by angelegg** [comment]
@metaprime  Hmm,This has not worked since 2 days ago. It halted at first download. It does not make sense to me. Anyway,you'd better not marge,maybe.

**Comment by Phenrei** [comment]
There appear to be download token issues after the first page, so everything throws back a 504. It's likely a cookie issue. I'm going to attempt to roll the obtaining of the download link into the step right before download so we don't obtain outdated tokens, and ensure all cookies are going forward/being re-obtained. For now I'd leave this pull on standby.

**Comment by poplipopatpotty** [comment]
@metaprime please help i m new... my queries are as follows:
1. how to download devianart ripper java (changed one) file from this github ?
2. i can replace then do i have to run build.bat and deploy .bat ? is this correct

please help me soon
as i want to download full gallery of greenmapple17 from devianart

also i couldnt identify if this error is rectified or not....hope it is
and is there any kind of coding that can bid gallery downloads into individual dolders just like those of devianart profile has in their uploads

**Comment by poplipopatpotty** [comment]
@Phenrei please anyone help

**Comment by metaprime** [comment]
@poplipopatpotty In order to get an update you'll need to get the version of the project that contains the update (the user's branch that made this pull request) and build according to the instructions in the README: https://github.com/4pr0n/ripme#compiling--building.

If you're not comfortable with Git or compiling software projects from the source code, the best thing to do is to wait for a new release which includes the fix you need.

**Comment by metaprime** [comment]
@poplipopatpotty There's a preview release available which includes a different fix for the deviantArt ripper, see: https://github.com/4pr0n/ripme/pull/516#issuecomment-298254520

**Comment by metaprime** [comment]
@Phenrei @angelegg @rautamiekka Any update?

**Comment by andrerdxd** [comment]
any news about this? it still happens to me

**Comment by cyian-1756** [comment]
@andrerdxd This repo is pretty much dead, all development has moved to https://github.com/RipMeApp/ripme

**Comment by rautamiekka** [comment]
Works perfectly to me ... Let's continue over at the successor linked above.

**Pull request closed without merging**
