### PR TITLE
added ripper for Jagodibuja.com

### PR DESCRIPTION
**Pull request by cyian-1756**
I added a ripper for the living with gamer girl and hipster girl webcomic from Jagodibuja.com

test link http://www.jagodibuja.com/webcomic-living-with-hipstergirl-and-gamergirl-english/

### CODE REVIEW

**Comment by metaprime** [comment]
Seems awfully specific, but from a glance at the website this might be the only specific content?

**Comment by metaprime** [comment]
Missing semicolon. Ripper hangs seemingly forever before doing anything (no output to indicate what is going on). Any reason not to start ripping files as they are detected?

**Comment by cyian-1756** [comment]
@metaprime 

> Seems awfully specific, but from a glance at the website this might be the only specific content?

There are other comics on the site that I over looked, I'm adding support for them now

> Missing semicolon. After fixing that, ripper hangs seemingly forever before doing anything (no output to indicate what is going on). Any reason not to start ripping files as they are detected?

My latest commit adds ASAP ripping and adds the missing semi colon

**Comment by cyian-1756** [comment]
@metaprime The ripper now can rip all comics from Jagodibuja.com

**Pull request merged**
