### PR TITLE
Updated working tumblr auth key

### PR DESCRIPTION
**Pull request by jgibson02**

### CODE REVIEW

**Comment by metaprime** [comment]
How permanent is this update? Will this need to be updated every so often?

**Comment by jgibson02** [comment]
I updated it twice because I found that by changing the key found in the tumblr ripper was not sufficient, it was being overridden by the one located in rip.properties. As for how permanent this solution is, that I'm unaware of. We would have to research into why the original tumblr auth key failed.

**Comment by metaprime** [comment]
In that case I think you might be missing part of your change? Only one line changed: src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java:32

**Comment by jgibson02** [comment]
You're right, it mistakenly does not include the changed rip.properties. I will close this pull request and create another with both files changed.

**Comment by metaprime** [comment]
Tip: you can push to the same branch and it will update this pull request automatically (if it's open at the time you update your branch). (No need to make a new pull request.) Either way is fine, though.

**Pull request closed without merging**
