### PR TITLE
Added xhamsters new cdn domain

### PR DESCRIPTION
**Pull request by cyian-1756**
I added xhamsters new cdn

test albums

https://xhamster.com/photos/gallery/7706811/jada_stevens_does_yoga_for_ass_parade.html

https://xhamster.com/photos/gallery/7706810/manoli_eeuu.html

### CODE REVIEW

**Comment by metaprime** [comment]
Not sure what this ended up fixing. The above links seem to rip properly even without this patch. Even the link from the original issue works: https://xhamster.com/photos/gallery/4893071/jennifer_lopez.html

From the log, it looks like there was a redirect, maybe because the CDN was temporarily down? This change greedily does the redirect automatically without trying the CDN, and might be bad for performance or result in bans. Not sure we should take this change.

**Comment by cyian-1756** [comment]
> The above links seem to rip properly even without this patch.

Testing it today it seems that it does now work

> This change greedily does the redirect automatically without trying the CDN, and might be bad for performance or result in bans. Not sure we should take this change.

I say lets leave the ripper as it was for now. If the issue reappears this can be merged later

**Comment by cyian-1756** [comment]
@metaprime It looks like xhamster uses different cdn domains for different areas which is why we can download without the patch and grml32 can't. I'll change my PR a bit to only change the cdn that's 302ing

**Comment by cyian-1756** [comment]
@metaprime 

> This change greedily does the redirect automatically without trying the CDN

I found the issue with xhcdn.com. xhcdn.com now seems to be a thumbnail only cdn (https://ept.xhcdn.com/000/047/774/302_100.jpg works fine being a thumbnail, but https://ept.xhcdn.com/000/047/774/302_1000.jpg 302s being a full sized image)

It looks like upt.xhcdn.com is also a thumbnail only cdn which is why the oringal ripper replaced it with up.xhamster

**Comment by metaprime** [comment]
@cyian-1756 Are you saying your latest change should fix this problem? I still wasn't able to repro the original problem.

**Comment by cyian-1756** [comment]
@metaprime

> Are you saying your latest change should fix this problem?

Yes.

**Comment by cyian-1756** [comment]
@metaprime Can I get an ETA on when this will be merged?

**Comment by metaprime** [comment]
@cyian-1756 Sorry, I still had it in my head that this PR was for a problem we couldn't repro. I'll get this merged as soon as I have a chance to test it out. Unfortunately my time has been spread pretty thin lately.

**Comment by metaprime** [comment]
LGTM

**Comment by grml32** [comment]
This still is not working on my end :-(

**Comment by cyian-1756** [comment]
Oh fucking xhamster. Their using the wrong cert for their ep cdn which is causing java to freak out. 

I'll make some changes to the ripper so it only using http.

Until then you can use the `only save urls` option, mass edit https to http (Any good text editor should have a replace all feature) and then just use some mass downloader (like wget or uget)

**Comment by cyian-1756** [comment]
@grml32 I made a PR fixing the issue [here](https://github.com/4pr0n/ripme/pull/520). 

Sorry that I missed this issue the first time around, but for whatever reason I've never hit the ep. subdomain on xhamster so I was unable to test my code to make sure it worked

**Comment by grml32** [comment]
Thanks for the fix :-)
but since i m not a programmer, i dont know how to integrate it in current version as its still not working for on 1.4.9  :-(

**Comment by cyian-1756** [comment]
@grml32 You'll have to wait for it to be merged into master and an update to be put out

**Comment by metaprime** [comment]
@cyian-1756 @grml32 The fix is now merged. Sorry for the delay.

**Pull request merged**
