### PR TITLE
Added deviantART description ripping

### PR DESCRIPTION
**Pull request by Wiiplay123**
It needs some work, notably the description text file doesn't have
prefix. Also, fixed a resource leak in Utils.java
Finally figured out that I'm supposed to fork and THEN pull.

### CODE REVIEW

**Comment by 4pr0n** [comment]
> It needs some work

Feel free to make more pull requests in the future.

**Comment by Wiiplay123** [comment]
It works! Thanks for including it in the update!

**Comment by micnorian14** [comment]
Now how can we disable it? I have no need for as many text files as there are images - thousands in some cases. A checkbox to toggle it is not present....

**Comment by Wiiplay123** [comment]
Oh that's actually a really good point... :disappointed:

Don't have time to add a toggle for it, but you could edit the code for it if you want to add that!

**Pull request merged**
